#!/bin/bash

#####################################################################################
# Copyright Glyfo Company. 2022. All Rights Reserved.                               #
# Apache License, Version 2.0. See LICENSE file in the project root for details.    #
# name    : Command Line Tool to deploy Smart Contract on Sui                       #
# website : glyfo.com                                                               #
# support : hello@glyfo.com                                                         #
#####################################################################################

# ---------------------- TIPS -------------------------------
#   echo $PWD          -  regular dollar char for outer (i.e. local) variables, e.g. 
#   echo \$PWD         -  escaped dollar char for inner (i.e. remote) variables, e.g.


## ----------------------  GLOBAL --------------------------
_path="/usr/local/sui/bin:/usr/local/cargo/bin:/bin:/usr/bin"

b=$(tput bold)
n=$(tput sgr0)

## ----------------------  UTIL FUNCTION ---------------------


echo_help () {
   echo "${n} Usage: ${b} glyclt ${n}"
   echo_setup 
   echo ""
   echo "v0.2.1"
   exit
}

echo_setup () {
echo "${b}+ setup${n}       : Handler Sui Node 
     + status   : Validate if suiX is Running on Enviroment 
     + build    : Deploy & Install Enviroment to Develop using Sui Blockchain 
     + login    : login into the Container 
     + reset    : Restart Container ( Stop & Start ) 
     + stack    : Show All Stack Version 
     + delete   : Delete Container" 
}

## ----------------------  BEGIN SETUP --------------------------
if [ "$1" = "setup" ]
then
   case "$2" in 
   build)
   docker stop suiX
   docker rm suiX
   docker pull docker pull mysten/sui-node:main 
   docker run  --name suiX  -id rust tail -f /dev/null
   docker exec -i suiX /bin/bash -s <<EOF
          uname -a
          apt-get -qq update                                                                                                        > /dev/null
          apt-get -qq upgrade                                                                                                       > /dev/null
          apt-get -qq install -y cmake libssl-dev libclang-dev net-tools --no-install-recommends apt-utils                          > /dev/null
          rustup update stable                                                                                                      > /dev/null
          export PATH=$_path
          cargo install --locked --git https://github.com/MystenLabs/sui.git --branch "devnet" sui sui-gateway                      > /dev/null
          echo '----------------------- Building Sui ----------------------------'
          sleep 1
          exit
EOF
   exit
;;
   status)
    if ($( docker ps --filter status=running  --format "table {{.Names}}" | grep suiX > /dev/null )) ; then
      echo "suiX is Running !!!"
    fi
    exit   
;;
   login)
    docker exec -it suiX /bin/bash
    exit
;;
   reset)
    echo "Stop Container"
    docker stop  $(docker ps -a |grep suiX |awk '{ print $1 }' )
    echo "Start Container"
    docker start $(docker ps -a |grep suiX |awk '{ print $1 }' )
    exit
;;
   delete)
    echo "Delete Container Enviroment"
    docker stop suiX
    docker rm suiX
    exit
;;
   stack)
    docker exec -i suiX /bin/bash -s <<EOF
    export PATH=$_path
    echo '----------------------- Release  --------------------'
    git --version |awk '{print "git\t\t\t| " \$3 }'
    rustc -V |awk '{print "rustc\t\t\t| " \$2 }'
    cargo -V |awk '{print "cargo\t\t\t| " \$2 }' 
    sui -V|awk '{print "sui\t\t\t| " \$2 }' 
   exit
EOF
   exit
;;
   *) 
   echo_setup
   exit
;; 
esac
fi

## ----------------------  END SETUP ----------------------------

## ----------------------  MAIN  ------------------------------

case "$1" in
help)
echo "help"
;; 
*)
echo_help
;;
esac
