#!/bin/bash

#####################################################################################
# Copyright Glyfo Company. 2023. All Rights Reserved.                               #
# Apache License, Version 2.0. See LICENSE file in the project root for details.    #
# name    : Command Line Tool to deploy Smart Contract on Sui                       #
# website : glyfo.com                                                               #
# support : support@glyfo.com                                                         #
#####################################################################################

# ---------------------- TIPS -------------------------------
#   echo $PWD          -  regular dollar char for outer (i.e. local) variables, e.g. 
#   echo \$PWD         -  escaped dollar char for inner (i.e. remote) variables, e.g.


## ----------------------  GLOBAL --------------------------
_path="/usr/local/sui/bin:/usr/local/cargo/bin:/bin:/usr/bin"

b=$(tput bold)
n=$(tput sgr0)

## ----------------------  UTIL FUNCTION ---------------------


echo_help () {
   echo "${n} Usage: ${b} glyclt ${n}"
   echo_setup 
   echo ""
   echo "v0.3.3"
   exit
}

echo_setup () {
echo "${b}+ setup${n}       : manage Sui container
     + wallet   : Genera Wallet A & B 
     + transfer : Deploy and install the required software on container
     + stack    : Current Stack  
}

## ----------------------  BEGIN SETUP --------------------------
   case "$1" in 
   wallet)
      cd sui
      mkdir A
      cd B 
      sui keytool generate ed25519 word18  > /dev/null
      cd ..
      mkdir B
      cd B
      sui keytool generate ed25519 word18  > /dev/null
      sui keytool show                                                                                            
   exit
   delete)
    echo "Delete Container Enviroment"
    docker stop suiX
    docker rm suiX
    exit
;;
   info)
    docker exec -i suiX /bin/bash -s <<EOF
    export PATH=$_path
    echo '----------------------- Release  --------------------'
    git --version |awk '{print "git\t\t\t| " \$3 }'
    rustc -V |awk '{print "rustc\t\t\t| " \$2 }'
    cargo -V |awk '{print "cargo\t\t\t| " \$2 }' 
    sui -V|awk '{print "sui\t\t\t| " \$2 }' 
   exit
EOF
   exit
;;
   *) 
   echo_setup
   exit
;; 
esac
fi

## ----------------------  END SETUP ----------------------------

## ----------------------  MAIN  ------------------------------

case "$1" in
help)
echo "help"
;; 
*)
echo_help
;;
esac
